# Generated by Django 5.1.2 on 2024-10-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('card', 'Card'), ('cash', 'Cash')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('success', models.BooleanField()),
                ('error_code', models.IntegerField(blank=True, null=True)),
                ('change_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coin_types', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
